### ISSUE TITLE
Questions regarding data split

### ISSUE THREAD

**Issue by lala-sean** [CUHK-AIM-Group/EndoSparse#3]
Hi @XGGNet, thanks for this great work. Can I ask for some details regarding the evaluation? like how you split the frames into the sparse training set and evaluation set? Thank you so much!

**Comment by Beilinlin** [comment]
Same question! @ZhihaoPENG-CityU @XGGNet @yifliu3 @LiuHengyu321 @lala-sean

**Comment by chenxinli001** [comment]
Thank you for your interest. We follow the common train-test split setting in EndoNeRF/EndoGaussian (https://github.com/CUHK-AIM-Group/EndoGaussian) that splits training and testing images in a 7:1 ratio, with the test images are evenly sampled. When the sparse-view setting is imposed, we further evenly sample k views from the training views and discard the remaining.

That is to say, you can just use the dataloder in EndoGaussian and perform even k view sampling in the training view to implement sparse-view setting.

**Comment by ZhihaoPENG-CityU** [comment]
> Same question! @ZhihaoPENG-CityU @XGGNet @yifliu3 @LiuHengyu321 @lala-sean

Thank you for your inquiry.

**Comment by Beilinlin** [comment]
Thank you very much for your explanation! Sorry to bother you, but I have one more question: Do I need to reinitialize the `poses_bunds.npy` file in the EndoNeRF dataset using COLMAP with the three sparse views, or can I use it directly? @XGGNet

**Comment by chenxinli001** [comment]
The standard sparse-view setting follows the case using COLMAP to initialize Guassians with only the avaliable sparse views. But, if you just wanna have a quick try, the default initialization with all views can also be used directly to get some insights at first.

**Comment by Beilinlin** [comment]
Certainly! Here’s the translation of your message into English:

---

Thank you very much for your prompt reply! So I would like to ask whether the point cloud initialization is done using COLMAP, rather than obtaining the point cloud through reprojection from predicted depth maps? If so, since you have used Depth-Anything to predict the depth maps, why not utilize these depth maps to obtain the point cloud through reprojection? Wouldn't this approach yield more point clouds and be    @XGGNet 

---

**Comment by Beilinlin** [comment]
Thank you very much for your prompt reply! 
So I would like to ask whether the point cloud initialization is done using COLMAP, rather than obtaining the point cloud through reprojection from predicted depth maps? If so, since you have used Depth-Anything to predict the depth maps, why not utilize these depth maps to obtain the point cloud through reprojection? Wouldn't this approach yield more point clouds and be  @XGGNet

**Comment by chenxinli001** [comment]
The dataloader in EndoGuassian supports multiple initialization, including COLMAP and back projection from depth maps. We use the depth re-projection from the depth at the avaliable limited views, if I'm not mistaken.
